from pathlib import Path


TEST_DATA_FOLDER = Path(__file__).parent / 'data'

PYTHON_DATA_FOLDER = TEST_DATA_FOLDER / 'python'

JAVA_DATA_FOLDER = TEST_DATA_FOLDER / 'java'

KOTLIN_DATA_FOLDER = TEST_DATA_FOLDER / 'kotlin'

SPRING_DATA_FOLDER = TEST_DATA_FOLDER / 'spring'

JS_DATA_FOLDER = TEST_DATA_FOLDER / 'js'
