# The configuration was made using the following table: https://bit.ly/3Kvz0nK

run:
  tests: false

output:
  uniq-by-line: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - unused
    - asciicheck
    - bodyclose
    - cyclop
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - funlen
    - gochecknoglobals
    - goconst
    - gomnd
    - lll  # Metric: LINE_LEN
    - maintidx
    - misspell
    - nilerr
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    # ===============
    #   Metalinters
    # ===============
    - gosimple
    - govet
    - staticcheck
    - gocritic
    - revive
    - stylecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  cyclop: # Metric: CYCLOMATIC_COMPLEXITY
    max-complexity: -1
    skip-tests: true
  funlen: # Metric: FUNC_LEN
    lines: 1
    statements: -1
  goconst:
    ignore-calls: false
    ignore-tests: true
  gomnd:
    ignored-numbers:
      - "-1"
      - "2"
      - "10"
    ignored-functions:
      - "time.Sleep"
  maintidx: # Metric: MAINTAINABILITY
    under: 100
  usestdlibvars:
    http-method: true
    http-status-code: true
    time-weekday: true
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
  varnamelen:
    max-distance: 10
    min-name-length: 3
    ignore-names:
      - db
      - tx
    ignore-decls:
      - c echo.Context
      - t testing.T
      - i int
      - T any
      - m map[string]int
  # ===============
  #   Metalinters
  # ===============
  revive:
    enable-all-rules: false
    rules:
      - name: time-equal
      - name: var-declaration
      - name: context-as-argument
      - name: error-return
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: indent-error-flow
      - name: empty-block
      - name: superfluous-else
      - name: confusing-naming
      - name: get-return
      - name: unnecessary-stmt
      - name: bool-literal-in-expr
      - name: range-val-address
      - name: duplicated-imports
      - name: unused-receiver
      - name: early-return
      - name: identical-branches
      - name: unexported-naming
  govet:
    disable-all: true
    enable:
      - atomic
      - bools
      - composites
      - copylocks
      - loopclosure
      - lostcancel
      - printf
      - stdmethods
      - structtag
      - unreachable
      - unusedresult
  gosimple:
    checks: [
      "-*",  # Disable all inspections by default
      "S1000",
      "S1001",
      "S1003",
      "S1004",
      "S1005",
      "S1006",
      "S1007",
      "S1008",
      "S1009",
      "S1010",
      "S1011",
      "S1012",
      "S1016",
      "S1017",
      "S1018",
      "S1019",
      "S1020",
      "S1021",
      "S1024",
      "S1025",
      "S1028",
      "S1029",
      "S1030",
      "S1031",
      "S1032",
      "S1033",
      "S1034",
      "S1035",
      "S1036",
      "S1038",
      "S1039",
      "S1040",
    ]
  staticcheck:
    checks: [
      "-*", # Disable all inspections by default
      "SA1000",
      "SA1001",
      "SA1002",
      "SA1003",
      "SA1006",
      "SA1007",
      "SA1008",
      "SA1010",
      "SA1011",
      "SA1012",
      "SA1013",
      "SA1014",
      "SA1015",
      "SA1018",
      "SA1021",
      "SA1023",
      "SA1024",
      "SA1025",
      "SA1026",
      "SA1028",
      "SA1029",
      "SA1030",
      #
      "SA2000",
      "SA2001",
      "SA2003",
      #
      "SA4001",
      "SA4003",
      "SA4004",
      "SA4005",
      "SA4008",
      "SA4009",
      "SA4011",
      "SA4012",
      "SA4013",
      "SA4014",
      "SA4015",
      "SA4016",
      "SA4017",
      "SA4020",
      "SA4021",
      "SA4022",
      "SA4024",
      "SA4026",
      "SA4028",
      "SA4029",
      "SA4030",
      "SA4031",
      #
      "SA5000",
      "SA5001",
      "SA5003",
      "SA5004",
      "SA5007",
      "SA5010",
      "SA5012",
      #
      "SA6000",
      "SA6002",
      "SA6005",
      #
      "SA9006",
    ]
  stylecheck:
    checks: [
      "-*", # Disable all inspections by default
      "ST1015",
      "ST1016",
      "ST1017",
    ]
  gocritic:
    enabled-checks:
      - dupCase
      - dupSubExpr
      - exitAfterDefer
      - assignOp
      - elseif
      - ifElseChain
      - newDeref
      - switchTrue
      - underef
      - unlambda
      - unslice
      - valSwap
      - appendCombine
      - stringXbytes
