# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hyperstyle/src/python/review/inspectors/ij_python/proto/model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nChyperstyle/src/python/review/inspectors/ij_python/proto/model.proto\x12\x37hyperstyle.src.python.review.inspectors.ij_python.proto\"m\n\x04\x43ode\x12\x0c\n\x04text\x18\x01 \x01(\t\x12W\n\nlanguageId\x18\x02 \x01(\x0e\x32\x43.hyperstyle.src.python.review.inspectors.ij_python.proto.LanguageId\"^\n\x07Problem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tinspector\x18\x02 \x01(\t\x12\x12\n\nlineNumber\x18\x03 \x01(\x04\x12\x0e\n\x06offset\x18\x04 \x01(\x04\x12\x0e\n\x06length\x18\x05 \x01(\x04\"f\n\x10InspectionResult\x12R\n\x08problems\x18\x01 \x03(\x0b\x32@.hyperstyle.src.python.review.inspectors.ij_python.proto.Problem\"p\n\x07Service\x12\x0c\n\x04name\x18\x01 \x01(\t\x12W\n\nlanguageId\x18\x02 \x01(\x0e\x32\x43.hyperstyle.src.python.review.inspectors.ij_python.proto.LanguageId\"\x1c\n\nInitResult\x12\x0e\n\x06status\x18\x01 \x01(\x04*.\n\nLanguageId\x12\n\n\x06Python\x10\x00\x12\n\n\x06kotlin\x10\x01\x12\x08\n\x04Java\x10\x02\x32\xc1\x02\n\x15\x43odeInspectionService\x12\x95\x01\n\x07inspect\x12=.hyperstyle.src.python.review.inspectors.ij_python.proto.Code\x1aI.hyperstyle.src.python.review.inspectors.ij_python.proto.InspectionResult\"\x00\x12\x8f\x01\n\x04init\x12@.hyperstyle.src.python.review.inspectors.ij_python.proto.Service\x1a\x43.hyperstyle.src.python.review.inspectors.ij_python.proto.InitResult\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hyperstyle.src.python.review.inspectors.ij_python.proto.model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LANGUAGEID._serialized_start=583
  _LANGUAGEID._serialized_end=629
  _CODE._serialized_start=128
  _CODE._serialized_end=237
  _PROBLEM._serialized_start=239
  _PROBLEM._serialized_end=333
  _INSPECTIONRESULT._serialized_start=335
  _INSPECTIONRESULT._serialized_end=437
  _SERVICE._serialized_start=439
  _SERVICE._serialized_end=551
  _INITRESULT._serialized_start=553
  _INITRESULT._serialized_end=581
  _CODEINSPECTIONSERVICE._serialized_start=632
  _CODEINSPECTIONSERVICE._serialized_end=953
# @@protoc_insertion_point(module_scope)
