# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hyperstyle.src.python.review.inspectors.ij_python.proto import model_pb2 as hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2


class CodeInspectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.inspect = channel.unary_unary(
                '/hyperstyle.src.python.review.inspectors.ij_python.proto.CodeInspectionService/inspect',
                request_serializer=hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2.Code.SerializeToString,
                response_deserializer=hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2.InspectionResult.FromString,
                )
        self.init = channel.unary_unary(
                '/hyperstyle.src.python.review.inspectors.ij_python.proto.CodeInspectionService/init',
                request_serializer=hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2.Service.SerializeToString,
                response_deserializer=hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2.InitResult.FromString,
                )


class CodeInspectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeInspectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.inspect,
                    request_deserializer=hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2.Code.FromString,
                    response_serializer=hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2.InspectionResult.SerializeToString,
            ),
            'init': grpc.unary_unary_rpc_method_handler(
                    servicer.init,
                    request_deserializer=hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2.Service.FromString,
                    response_serializer=hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2.InitResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hyperstyle.src.python.review.inspectors.ij_python.proto.CodeInspectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CodeInspectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hyperstyle.src.python.review.inspectors.ij_python.proto.CodeInspectionService/inspect',
            hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2.Code.SerializeToString,
            hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2.InspectionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hyperstyle.src.python.review.inspectors.ij_python.proto.CodeInspectionService/init',
            hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2.Service.SerializeToString,
            hyperstyle_dot_src_dot_python_dot_review_dot_inspectors_dot_ij__python_dot_proto_dot_model__pb2.InitResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
