# This config was created based on the default config for Detekt 1.18.0
# using the following table: https://bit.ly/2V2kCyi

# Some inspections have been commented out due to problems with upgrading to version 1.18.0.
# The current config contains only those inspections that work on version 1.14.2.

build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
  # complexity: 2
  # LongParameterList: 1
  # style: 1
  # comments: 1

config:
  validation: true
  warningsAsErrors: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

processors:
  active: true
  exclude:
    - 'DetektProgressListener'
  # - 'KtFileCountProcessor'
  # - 'PackageCountProcessor'
  # - 'ClassCountProcessor'
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
  # - 'FindingsReport'
    - 'FileBasedFindingsReport'

# TODO: Uncomment inspections when upgrading Detekt to version 1.18.0+. Don't forget to uncomment them in issue_types.

comments:
  active: false
  AbsentOrWrongFileLicense:
    active: false
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
#  DeprecatedBlockTag:
#    active: false
  EndOfSentenceFormat:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 0
  ComplexInterface:
    active: false
  ComplexMethod:
    active: true
    threshold: 0
    ignoreSingleWhenExpression: true
    ignoreSimpleWhenEntries: true
    ignoreNestingFunctions: false
  LabeledExpression:
    active: false
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 0
  LongParameterList:
    active: true
  MethodOverloading:
    active: false
#  NamedArguments:
#    active: false
  NestedBlockDepth:
    active: true
    threshold: 4
  ReplaceSafeCallChainWithRun:
    active: false
  StringLiteralDuplication:
    active: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 21
    thresholdInClasses: 21
    thresholdInObjects: 21

coroutines:
  active: false
  GlobalCoroutineUsage:
    active: false
  RedundantSuspendModifier:
    active: false
#  SleepInsteadOfDelay:
#    active: false
  SuspendFunWithFlowReturnType:
    active: false

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyTryBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: true
  InstanceOfCheckForException:
    active: false
  NotImplementedDeclaration:
    active: false
#  ObjectExtendsThrowable:
#    active: false
  PrintStackTrace:
    active: false
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: false
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: false
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false

formatting:
  active: true
  android: false
  autoCorrect: false
  AnnotationOnSeparateLine:
    active: false
  AnnotationSpacing:
    active: false
  ArgumentListWrapping:
    active: false
  ChainWrapping:
    active: true
  CommentSpacing:
    active: true
  EnumEntryNameCase:
    active: true
  Filename:
    active: false
  # Duplicated by NewLineAtEndOfFile
  FinalNewline:
    active: false
  ImportOrdering:
    active: true
  Indentation:
    active: true
  # Duplicated by MaxLineLength
  MaximumLineLength:
    active: false
  # Duplicated by ModifierOrder
  ModifierOrdering:
    active: false
  MultiLineIfElse:
    active: true
  NoBlankLineBeforeRbrace:
    active: false
  NoConsecutiveBlankLines:
    active: true
  # Duplicated by EmptyClassBlock
  NoEmptyClassBody:
    active: false
  NoEmptyFirstLineInMethodBlock:
    active: false
  NoLineBreakAfterElse:
    active: true
  NoLineBreakBeforeAssignment:
    active: true
  NoMultipleSpaces:
    active: true
  NoSemicolons:
    active: true
  # Duplicated by TrailingWhitespace
  NoTrailingSpaces:
    active: false
  # Duplicated by OptionalUnit
  NoUnitReturn:
    active: false
  # Duplicated by UnusedImports
  NoUnusedImports:
    active: false
  # Duplicated by WildcardImport
  NoWildcardImports:
    active: false
  # Duplicated by PackageNaming
  PackageName:
    active: false
  ParameterListWrapping:
    active: true
#  SpacingAroundAngleBrackets:
#    active: false
  SpacingAroundColon:
    active: true
  SpacingAroundComma:
    active: true
  SpacingAroundCurly:
    active: true
  SpacingAroundDot:
    active: true
  SpacingAroundDoubleColon:
    active: false
  SpacingAroundKeyword:
    active: true
  SpacingAroundOperators:
    active: true
  SpacingAroundParens:
    active: true
  SpacingAroundRangeOperator:
    active: true
#  SpacingAroundUnaryOperator:
#    active: false
  SpacingBetweenDeclarationsWithAnnotations:
    active: false
  SpacingBetweenDeclarationsWithComments:
    active: false
  StringTemplate:
    active: true

naming:
  active: true
#  BooleanPropertyNaming:
#    active: true
  ClassNaming:
    active: true
  ConstructorParameterNaming:
    active: true
  EnumNaming:
    active: true
  ForbiddenClassName:
    active: false
  FunctionMaxLength:
    active: false
  FunctionMinLength:
    active: false
  FunctionNaming:
    active: true
  FunctionParameterNaming:
    active: true
  InvalidPackageDeclaration:
    active: false
  MatchingDeclarationName:
    active: false
  MemberNameEqualsClassName:
    active: false
#  NoNameShadowing:
#    active: false
  NonBooleanPropertyPrefixedWithIs:
    active: true
  ObjectPropertyNaming:
    active: true
  PackageNaming:
    active: true
  TopLevelPropertyNaming:
    active: true
  VariableMaxLength:
    active: false
  VariableMinLength:
    active: false
  VariableNaming:
    active: true

performance:
  active: true
  ArrayPrimitive:
    active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
#  AvoidReferentialEquality:
#    active: false
#  CastToNullableType:
#    active: false
  Deprecation:
    active: false
#  DontDowncastCollectionTypes:
#    active: false
#  DoubleMutabilityForCollection:
#    active: false
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
#  ExitOutsideMain:
#    active: false
  ExplicitGarbageCollectionCall:
    active: true
  HasPlatformType:
    active: false
  IgnoredReturnValue:
    active: false
  ImplicitDefaultLocale:
    active: false
  ImplicitUnitReturnType:
    active: false
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: false
  MapGetWithNotNullAssertionOperator:
    active: true
  MissingWhenCase:
    active: true
  NullableToStringCall:
    active: true
  RedundantElseInWhen:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
#  UnreachableCatchBlock:
#    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
#  UnusedUnaryOperator:
#    active: true
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true

style:
  active: true
  ClassOrdering:
    active: false
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: false
  DataClassShouldBeImmutable:
    active: false
#  DestructuringDeclarationWithTooManyEntries:
#    active: false
  EqualsNullCall:
    active: true
  EqualsOnSignatureLine:
    active: false
  ExplicitCollectionElementAccessMethod:
    active: false
  ExplicitItLambdaParameter:
    active: false
  ExpressionBodySyntax:
    active: false
  ForbiddenComment:
    active: false
  ForbiddenImport:
    active: false
  ForbiddenMethodCall:
    active: false
  ForbiddenPublicDataClass:
    active: false
  ForbiddenVoid:
    active: false
  FunctionOnlyReturningConstant:
    active: false
  LibraryCodeMustSpecifyReturnType:
    active: true
  LibraryEntitiesShouldNotBePublic:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  MagicNumber:
    active: true
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  MayBeConst:
    active: true
  ModifierOrder:
    active: true
#  MultilineLambdaItParameter:
#    active: false
  NestedClassesVisibility:
    active: false
  NewLineAtEndOfFile:
    active: false
  NoTabs:
    active: false
#  ObjectLiteralToLambda:
#    active: false
  OptionalAbstractKeyword:
    active: true
  OptionalUnit:
    active: true
  OptionalWhenBraces:
    active: true
  PreferToOverPairSyntax:
    active: false
  ProtectedMemberInFinalClass:
    active: true
  RedundantExplicitType:
    active: true
#  RedundantHigherOrderMapUsage:
#    active: true
  RedundantVisibilityModifierRule:
    active: true
  ReturnCount:
    active: false
  SafeCast:
    active: true
  SerialVersionUIDInSerializableClass:
    active: false
  SpacingBetweenPackageAndImports:
    active: true
  ThrowsCount:
    active: false
  TrailingWhitespace:
    active: false
  UnderscoresInNumericLiterals:
    active: false
  UnnecessaryAbstractClass:
    active: true
  UnnecessaryAnnotationUseSiteTarget:
    active: false
  UnnecessaryApply:
    active: true
#  UnnecessaryFilter:
#    active: true
  UnnecessaryInheritance:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: false
  UnusedImports:
    active: true
  UnusedPrivateClass:
    active: true
  # TODO: Maybe we should activate it.
  UnusedPrivateMember:
    active: false
  UseArrayLiteralsInAnnotations:
    active: false
  UseCheckNotNull:
    active: true
  UseCheckOrError:
    active: true
  UseDataClass:
    active: true
  UseEmptyCounterpart:
    active: true
#  UseIfEmptyOrIfBlank:
#    active: true
  UseIfInsteadOfWhen:
    active: true
#  UseIsNullOrEmpty:
#    active: true
#  UseOrEmpty:
#    active: true
  UseRequire:
    active: true
  UseRequireNotNull:
    active: true
  UselessCallOnNotNull:
    active: true
  UtilityClassWithPublicConstructor:
    active: false
  VarCouldBeVal:
    active: true
  WildcardImport:
    active: true
